### ISSUE TITLE
使用的是 python3 吗？

### ISSUE THREAD

**Issue by huaerheima** [Chyroc/WechatSogou#1]
![image](https://cloud.githubusercontent.com/assets/15190450/15132926/fd8a9fb2-1690-11e6-9c2d-d9c3a4ff693a.png)
并没有在tools下找到myproxy和myrequest

**Comment by Chyroc** [comment]
已修复

**Comment by huaerheima** [comment]
有时间给你贡献点代码

**Comment by Chyroc** [comment]
谢谢啦~~

**Comment by huaerheima** [comment]
方便的话加一下你的QQ或者微信吧，可以方便交流，顺便交个朋友，我的微信：huaerheima 😊
