### ISSUE TITLE
获取文章只能10篇？

### ISSUE THREAD

**Issue by zilhua** [Chyroc/WechatSogou#10]
作者你好：
想请教一个问题，几种方式搜索文章/公众号，都只能搜10篇吗？

**Comment by Chyroc** [comment]
由于搜狗限制，所以是的，只有10。
但是你可以先获取所有历史数据，然后不断更新，这样就可以了。
获取所有数据的方法在demo/get_old里面

**Comment by Chyroc** [comment]
获取历史文章方法因接口屏蔽，已删除。
获取更新的文章是最近十篇。
