### ISSUE TITLE
有代理ip更换的参数吗 

### ISSUE THREAD

**Issue by leinue** [Chyroc/WechatSogou#141]
如题

**Comment by Chyroc** [comment]
你可以用代理ip获取到搜狗页面的文本，然后用本项目去解析。

**Comment by jeremylinlin** [comment]
@Chyroc 没理解您的意思。使用代理的意义不就是为了避免同一 IP 使用本项目的 API 对微信搜狗发送过多请求, 而导致弹出验证码而中断脚本的执行吗? 那如果脱离了本项目如何从搜狗得到数据呢?

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/142
