### ISSUE TITLE
get_gzh_artilce_by_history 出现填写code

### ISSUE THREAD

**Issue by qbaoma** [Chyroc/WechatSogou#144]
请问下 “get_gzh_artilce_by_history”这个方法执行后出现了这样的结果
please input code:

这是要填写什么？代码里面也没看明白。
求各位大大解答下，谢谢。

**Comment by Chyroc** [comment]
这是说明出现了验证码，验证码没有出现吗？

**Comment by qbaoma** [comment]
是的， 就像这样。
![image](https://user-images.githubusercontent.com/11188068/30192216-c6373c0c-9478-11e7-8400-bf670e457e0a.png)

**Comment by Chyroc** [comment]
我知道了，你是linux服务器吧？所以没有办法把图片显示出来，你在自己电脑上试试

**Comment by qbaoma** [comment]
二维码是自动显示的？我记得前几天还可以啊 就突然就变成这样了

**Comment by Chyroc** [comment]
1、你机器的系统是什么
2、你是自己电脑还是服务器
3、几天前还好好的，是指「可以出现验证码图片」还是「不会出现code字样」

**Comment by qbaoma** [comment]
1. centos 6.3 x64
2. 服务器
3. 不会出现code字样， 能返回正确的返回信息，包括文章信息，公众号信息等

**Comment by Chyroc** [comment]
结论
1、出现这样的情况是正常的
2、以前不出现是因为频率不高，没有触发搜狗或者微信的验证码，现在出现了
3、在桌面环境会弹出来一个验证码，因为你是服务器，所以无法显示验证码

解决方案
1、换桌面环境
2、等一段时间再使用本api
3、配置自动识别验证码的打码脚本（接入打码平台），具体可参考test目录下的一个例子 https://github.com/Chyroc/WechatSogou/blob/master/test/rk.py#L42-L61

**Comment by qhbmars911** [comment]
@Chyroc 请教下，identify_image_callback_by_hand手动输入正确的验证后，__get_by_unlock，跳出验证码，但是继续执行到resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))这步后，还是无法获取正确的公众号文章列表页面，是必须要Cookie吗？我看__set_cookie中获得的suv和snuid都为空，是这个原因吗？望解答
