### ISSUE TITLE
请问在阿里云ECS上出现需要输入验证码的时候该怎么解决？

### ISSUE THREAD

**Issue by hhlisme** [Chyroc/WechatSogou#146]
在在阿里云ECS上抓了几个公众号的文章之后就被要求需要please input code: 但我在ECS上找不到验证码放在哪个目录下（不在代码目录），请问该如何操作？或者有什么更好的避免二维码的方法么？

**Comment by Chyroc** [comment]
服务器上需要的是自动输入

打码平台 or 机器学习

**Comment by hhlisme** [comment]
能否找到那个二维码图片出现的位置然后手动输入呢？

**Comment by Chyroc** [comment]
这是服务器呀，难道你要下载这个图片，然后打开看？不符合实际情况

**Comment by hhlisme** [comment]
因为我想知道图片保存在什么位置然后写个机器学习算法去判断，不然没图片找不到不好写地址，对吧？

**Comment by Chyroc** [comment]
参见这个例子：https://github.com/Chyroc/WechatSogou/blob/master/test/rk.py#L42-L61

img参数就是图片的二进制数据，你可以自己写一个函数，把图片保存起来
