### ISSUE TITLE
get_gzh_article_by_history输入正确的验证码依然无法获取公众号文章列表页面数据

### ISSUE THREAD

**Issue by qhbmars911** [Chyroc/WechatSogou#165]
@Chyroc 请教下，identify_image_callback_by_hand手动输入正确的验证后，__get_by_unlock，跳出验证码，但是继续执行到resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))这步后，还是无法获取正确的公众号文章列表页面，是必须要Cookie吗？我看__set_cookie中获得的suv和snuid都为空，是这个原因吗？望解答

**Comment by Chyroc** [comment]
应该是的

**Comment by qhbmars911** [comment]
@Chyroc suv和snuid是怎么产生的，自己登录后取出来，放在/tmp/wechatsogou-cache目录文件中？另外，既然有了 suv和snuid的cookie，那验证码打码的意义何在？验证码打码对于suv和snuid的cookie没有任何帮助？只是单独验证通过而已，数据还是需要Cookie才能取到？

**Comment by Chyroc** [comment]
1、打码后出现这两个值，放到cookie里面
2、使用一段时间后这两个值会失效，所以需要中心打码
3、打字都不换行的吗

**Comment by qhbmars911** [comment]
@Chyroc 多谢答复。但我发现打码后，不会出现 suv和snuid，只会出现pgv_pvi、sig字段，是改版了吗？
我在浏览器中看也是 pgv_pvi、sig

**Comment by qhbmars911** [comment]
@Chyroc 另外，__set_cookie中由于
        suv = ws_cache.get('suv') if suv is None else suv
        snuid = ws_cache.get('snuid') if snuid is None else snuid
suv和snuid也一直为空，是不是不太对？
