### ISSUE TITLE
提示找不到模块，而且pip install wechatsogou安装失败

### ISSUE THREAD

**Issue by hellodabin** [Chyroc/WechatSogou#169]
![image](https://user-images.githubusercontent.com/12904775/35194719-c0b5d4e8-fef2-11e7-96a6-0d9318d06c2e.png)

**Comment by Chyroc** [comment]
安装失败报错是什么

**Comment by hellodabin** [comment]
抱歉，现在可以了，麻烦了 /抱拳

**Comment by hellodabin** [comment]
end
