### ISSUE TITLE
原始文章url

### ISSUE THREAD

**Issue by sinbh** [Chyroc/WechatSogou#17]
腾讯修改接口,获取原始文章url的msg_link为空,导致无法获取原始文章url

**Comment by Chyroc** [comment]
给个截图？刚刚看了一下还在的

**Comment by hyhero127** [comment]
问题确实存在，需要解决方案

**Comment by zhuliuxing** [comment]
我也碰到了这个问题，页面打开有时候有，有时候没有，有人发现规律了吗？
![wechat](https://cloud.githubusercontent.com/assets/17867395/20044249/3bf8bf16-a4d2-11e6-8a60-1191fc0fec29.JPG)

**Comment by sinbh** [comment]
@Chyroc  基本上大多数文章都没有了msg_link,目前没研究出解决办法,从历史文章倒是能拿到这个原文链接,不过历史不方便获取

![msg_link](https://cloud.githubusercontent.com/assets/12680855/20252835/c723d1fa-aa60-11e6-95e8-c478036870e4.png)

**Comment by Chyroc** [comment]
是的。
现在需要通过对原文进行抓取保存在自己服务器来实现了。

**Comment by longzhiwen888** [comment]
微信太坑了，很多文章得不到永久的链接了，都是临时的链接
