### ISSUE TITLE
当公众号搜索结果有多个时会有异常，没法爬取公众号连接

### ISSUE THREAD

**Issue by Estom** [Chyroc/WechatSogou#172]
[http://weixin.sogou.com/weixin?type=1&query=npudaily&ie=utf8&s_from=input&_sug_=y&_sug_type_=](url)

调用的函数为：
`ws_api.get_gzh_article_by_history('npudaily')`
异常为：
`list index out of range
`

**Comment by Chyroc** [comment]
能找到问题吗，可以的话可以顺便提pr修复一下。不然我放假看看

发自我的 iPhone

**Comment by Chyroc** [comment]
可以啊，搜索的结果一般都是好几个，会取第一个的

![image](https://user-images.githubusercontent.com/15604894/36473604-f34b7020-172f-11e8-91b4-d1b045c1d6e7.png)
