### ISSUE TITLE
请问为什么有的公众号明明存在，却用ws_api.get_gzh_info搜索不到？

### ISSUE THREAD

**Issue by potatos666** [Chyroc/WechatSogou#173]
比如‘AAPS论坛’

**Comment by Chyroc** [comment]
![image](https://user-images.githubusercontent.com/15604894/36473512-ab420762-172f-11e8-9d4b-a24361bdc023.png)


可以啊

**Comment by cocolizh** [comment]
> ![image](https://user-images.githubusercontent.com/15604894/36473512-ab420762-172f-11e8-9d4b-a24361bdc023.png)
> 
> 可以啊

现在好像不行了
