### ISSUE TITLE
爬出来的很多链接并不能够使用！

### ISSUE THREAD

**Issue by lsasta** [Chyroc/WechatSogou#177]
图片链接被防盗链拦住，还有其他文章内容链接并不能直接点击进去。希望作者提供一个原文链接。

**Comment by Chyroc** [comment]
1.图片你保存一下，然后引用自己保存的图片
2.文章内容也是，抓取的链接有有效期限制

**Comment by lsasta** [comment]
好的。

**Comment by lsasta** [comment]
还是用问题啊，就是文章内容另外保存了，但是文章内容里面的图片却不能加载出来的

**Comment by Chyroc** [comment]
文章和图片都保存，然后替换图片地址

**Comment by lsasta** [comment]
我试试吧

**Comment by slina1994** [comment]
你好，爬下来的链接放在哪个文件夹呢？没有找到呢？

**Comment by Chyroc** [comment]
你想放哪就放哪

发自我的 iPhone
