### ISSUE TITLE
输入验证码后报错如下， 该如何？

### ISSUE THREAD

**Issue by luofei614** [Chyroc/WechatSogou#178]
File "/usr/lib/python3.4/site-packages/wechatsogou/api.py", line 329, in get_gzh_article_by_history
    if 'profile_url' not in gzh_list:
TypeError: argument of type 'NoneType' is not iterable

**Comment by luofei614** [comment]
经查 输入验证码正常后 再调用抓取的URL 还是输入验证码的返回html，这个如何破呀……

**Comment by Chyroc** [comment]
你看下我最新的修改，然后改一下呢，还没有release 

发自我的 iPhone

**Comment by luofei614** [comment]
好的， 知道了。
