### ISSUE TITLE
所有接口调取之后无数据返回。。

### ISSUE THREAD

**Issue by love-311** [Chyroc/WechatSogou#179]
![image](https://user-images.githubusercontent.com/19263806/36719619-80dbfffe-1be0-11e8-9be0-6a7760f2cbd6.png)
如图，调取接口之后无返回，我是一个Python初学者，不知道哪里出了问题，希望能够得到你的答复。。

**Comment by Chyroc** [comment]
没有print

**Comment by love-311** [comment]
请原谅我这个小白，我以为api封装了打印。。
