### ISSUE TITLE
search_gzh_info无法取得内容

### ISSUE THREAD

**Issue by william2177** [Chyroc/WechatSogou#18]
你好，首先十分感谢你这个project。我的Python版本是2.7.9，在跑test.py的时候出现了api.py 198行gzh_info['url'] has no attribute 'getitem'的问题。我稍微看了一下，是因为search_gzh_info这个function没有获得任何内容，返回了一个空的list。里面所有的page.xpath(xxx)所返回的内容也都是空的，但是第40行的text我print出来确实取得了完整的html代码。不知道是xpath的那个module的版本还是什么导致的？麻烦告知一下解决方法，万分感谢！

**Comment by william2177** [comment]
追加问题：windows下运行是，遇到要输入验证码会跳出一图片查看器窗口，但是内容显示“Windows照片查看器无法打开此图片，因为此图片被删除或者位于不可用的位置”。

**Comment by william2177** [comment]
貌似这两个问题是连在一起的。。因为第一次验证码没有过。。所以后面再跑就会出现search_gzh_info找不到东西的问题。。

**Comment by Chyroc** [comment]
你好，验证码还是不能出现吗，是不是因为没有权限创建图片文件？

**Comment by william2177** [comment]
对啊，不过我换了一个方式。用webbrowser module来打开就好了.save到本地打开...可能是那个存tempfile的那个有点问题？


发自我的 iPhone
