### ISSUE TITLE
一些改进建议：近一月发文数、近一月平均阅读量、公众号Biz

### ISSUE THREAD

**Issue by ygihjsg1** [Chyroc/WechatSogou#182]
我做了一个搜狗爬虫，主要通过关键词获取公众号列表，目前我获取的信息有：
mp_title # 公众号名
mp_id # 公众号ID
biz # 公众号的biz参数
des # 公众号的功能简介
mon_push # 公众号近一个月的发文数量
mon_view # 公众号近一个月的平均阅读量
last_alive # 上次的发文时间戳

其中biz & mon_push & mon_view 三个数据对于公众号的分析和营销来说意义很大。
biz 获取方式为：从最近的一条文章内容中获取
mon_push & mon_view 获取方式为：在公众号列表页中有一个特殊的接口，可以通过这个特殊接口查询到。

悲伤的事情是，我写完后，才发现原来有大神的这个作品，相见恨晚。在这里提供一点自己的改进建议。

在此献上我的处女issue，希望有机会与作者深入交流。
Email: yhj#miemie.la

**Comment by Chyroc** [comment]
mon_push & mon_view 已加，名字不是这个

biz还要获取文章内容，暂时没有加，应该由用户自己获取
