### ISSUE TITLE
爬下来的链接,过一段时间就不能访问了,提示链接已经过期

### ISSUE THREAD

**Issue by ocswor** [Chyroc/WechatSogou#185]
RT
但是在微信内置的浏览器中可以正常访问

![default](https://user-images.githubusercontent.com/8704928/37080205-5c945d44-2220-11e8-949e-d43f48d14fce.png)

**Comment by Chyroc** [comment]
链接具有有效期。

如果需要长期访问，请保存链接里文章内容
