### ISSUE TITLE
怎么样才不用输入验证码

### ISSUE THREAD

**Issue by lisongjian** [Chyroc/WechatSogou#192]
# 直连
    ws_api = wechatsogou.WechatSogouAPI()
    ws_api.get_gzh_article_by_history(‘xxx’)
然后就要图片验证码`

**Comment by Chyroc** [comment]
1、间隔时间特别长
2、打码平台

**Comment by lisongjian** [comment]
恩，或者图片切片识别，好烦，还有微信公众号文章会过期怎么破？怎么不是爬长期的链接

**Comment by luzihang123** [comment]
“间隔时间特别长”的原因是什么呢？搜狗保存了用户的session？

**Comment by Chyroc** [comment]
反爬虫的策略吧，不能ban了你就永远ban吧，过一段时间就会给你自由

**Comment by luzihang123** [comment]
是否有第三种方法
3.大量使用代理ip，总有不需要验证码的情况（估计比打码平台费钱）

**Comment by Chyroc** [comment]
可以呀

**Comment by 631068264** [comment]
@Chyroc 你这库这么接打码平台 啊大哥

**Comment by Chyroc** [comment]
参考：https://github.com/Chyroc/WechatSogou/issues/221
