### ISSUE TITLE
1、有关于验证码的问题想要请教

### ISSUE THREAD

**Issue by 1664451365** [Chyroc/WechatSogou#198]
1、想要获取的结果
我想要获取程序生成的验证码保存在本地某个指定位置
我想要再将我的验证码数字传回某个函数使包继续运行
2、关注的问题
我需要修改的代码位置

请大神赐教！！

**Comment by Chyroc** [comment]
@1664451365 

https://github.com/Chyroc/WechatSogou/blob/master/test/test_api.py#L56-L59

https://github.com/Chyroc/WechatSogou/blob/master/test/rk.py#L42-L61

通过回调函数可以获取到验证码的二进制数据，返回的结果就是识别后的数字
