### ISSUE TITLE
如何使用代理

### ISSUE THREAD

**Issue by noark9** [Chyroc/WechatSogou#2]
测试了一下，如果一直连续爬的话，那么就过一段时间需要输入验证码
输入完成后，还是不能正确的爬取数据
看了下代理的设置，简单的把 `__get` 函数的 `proxy` 设置为 `True` 后，只是输出了代理服务器的 ip 并不能继续爬取

**Comment by Chyroc** [comment]
你好，经过测试，搜狗微信无法使用代理/失败/我目前没找到方案，推荐使用里面添加的手动或者打码平台的解决方案，或者直接更换电脑的ip。

**Comment by kongxu633** [comment]
可以用cookies池解决 不同代理IP获取cookie令牌 存入数据库 随机放入header 3小时换一批

**Comment by Chyroc** [comment]
@kongxu633 ,你好，有演示代码吗，我做的代理都失败了，不知道你成功了没有？
