### ISSUE TITLE
请问，我运行test.py时为何没报错却没得到任何结果？

### ISSUE THREAD

**Issue by zeeqchu** [Chyroc/WechatSogou#21]
@Chyroc  感谢Chyroc的分享，弱问一下，为何我运行test.py时没有报错，却没有得到任何结果？然后我再写什么命令都没有反应了，这可能是什么问题啊，麻烦了

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: C:\chuzi\work\Python27\WechatSogou-master\test.py =========
>>> 
>>> print 1
>>> 
![image](https://cloud.githubusercontent.com/assets/23495853/20354262/895f9f4e-ac58-11e6-8104-30c11814386b.png)

**Comment by Chyroc** [comment]
print(你获取的数据)

**Comment by zeeqchu** [comment]
@Chyroc 感谢回复指点~我是直接运行的test.py，然后print里面的变量也是没有反应，这里是运行结果。
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: C:\chuzi\work\Python27\WechatSogou-master\test.py =========
>>> print wechats
>>> print wechat_infos
>>> print wechat_articles
>>> print name
>>> print keywords
>>> 
是否是python环境设置有问题？我从来没遇到过运行一段程序不报错，却导致后面没法用了的情况。
我在test.py中每一行添加一句《print 1》，发现就是这两句执行后python环境就没反应了
from wechatsogou.tools import *
from wechatsogou import *
会是环境有问题么？
![image](https://cloud.githubusercontent.com/assets/23495853/20416114/bd153ae0-ad77-11e6-8b40-f83809185f5c.png)
