### ISSUE TITLE
文章标题带引号（"，&quot）的情况解析报错

### ISSUE THREAD

**Issue by inerve** [Chyroc/WechatSogou#23]
_get_gzh_article_by_url_dict -> _replace_html 时如果文章标题出现「"」引号，也会一样转换。导致eval的时候解析错误。

**Comment by inerve** [comment]
补充：其它字段应该也有类似问题，比如「digest」等

**Comment by Chyroc** [comment]
你好，有例子吗，给个公众号看看

**Comment by inerve** [comment]
比如：「摩托欧耶」moto-oy

**Comment by Chyroc** [comment]
@inerve 已修复

**Comment by inerve** [comment]
汗。。为什么删除了「basic.py」的「_deal_gzh_article_dict」方法？

**Comment by Chyroc** [comment]
这个还有用吗，我记得是处理历史文章的但是现在历史文章无法获取了

**Comment by Chyroc** [comment]
@inerve 改回来了，因为在测试另一个功能，误删了，抱歉~

**Comment by inerve** [comment]
赞作者，issue可以关闭了。
