### ISSUE TITLE
是接口失效了还是IP被封了

### ISSUE THREAD

**Issue by coinmeo** [Chyroc/WechatSogou#231]
![image](https://user-images.githubusercontent.com/40992146/54806094-fb457180-4cb3-11e9-8080-0b1fdb082924.png)
![image](https://user-images.githubusercontent.com/40992146/54806103-013b5280-4cb4-11e9-820b-6788c42e0324.png)
想请问一下 无论通过api里面的任何接口 获取的数据都是空的 该怎么办

**Comment by baby5** [comment]
应该是搜狗更新了新的反爬策略

**Comment by coinmeo** [comment]
> 应该是搜狗更新了新的反爬策略

那有没有什么办法推荐啊 我换了不同的网 都不行 感觉不是IP问题 用浏览器也可以访问到微信搜狗

**Comment by Ahaaaaaa** [comment]
@Chyroc 提了个PR，看一下

**Comment by coinmeo** [comment]
> @Chyroc 提了个PR，看一下

谢谢大神技术分享

**Comment by IKkSssDendi** [comment]
> @Chyroc提了个PR，看一下

谢谢大佬

**Comment by yqdaddy** [comment]
在这里是不是更好?@Ahaaaaaa @Chyroc 
def __set_cookie(self, suv=None, snuid=None, referer=None):
        suv = ws_cache.get('suv') if suv is None else suv
        snuid = ws_cache.get('snuid') if snuid is None else snuid
        _headers = {'Cookie': 'SUV={};SNUID={};'.format(suv, snuid)}
        **_headers = {'User-Agent': 'Mozilla/5.0 (Linux; U; Android 5.1; zh-cn; OPPO R9m Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.0.0 Mobile Safari/537.36 OppoBrowser/4.1.8'}**
        if referer is not None:
            _headers['Referer'] = referer
        return _headers

**Comment by Ahaaaaaa** [comment]
这个方法是__set_cookie，在这里面设置header感觉有点奇怪 @yqdaddy

**Comment by nimozzzz** [comment]
各位这个问题解决了吗？

**Comment by Cat-L** [comment]
> @Chyroc 提了个PR，看一下
用这个版本后出现问题：
![7 8HZ(~ H}G2 }JHN1R}{YO](https://user-images.githubusercontent.com/32644598/54890219-56a97680-4ee3-11e9-99be-9bda9f894097.png)
求助

**Comment by IKkSssDendi** [comment]
我也遇到了相同的问题，我是通过构造headers，WecahtSogouAPI(headers=headers)解决的，昨天测试的时候是没有问题的。

**Comment by isaac-cat** [comment]
求大佬更新啊

**Comment by haoyuanchanlai** [comment]
> > @Chyroc提了个PR，一下看
> > 用这个版本后出现问题：
> > 求助
> > ![7 8HZ（~H} G2} JHN1R} {YO](https://user-images.githubusercontent.com/32644598/54890219-56a97680-4ee3-11e9-99be-9bda9f894097.png)

![image](https://user-images.githubusercontent.com/48897387/54891147-56ab7580-4ee7-11e9-86cc-74bff0591694.png)
发送请求的时候，需要加上域名，不然就跳转失败了

**Comment by haoyuanchanlai** [comment]
![image](https://user-images.githubusercontent.com/48897387/54891392-2adcbf80-4ee8-11e9-94d3-4c9873fba973.png)
![image](https://user-images.githubusercontent.com/48897387/54891406-37f9ae80-4ee8-11e9-8883-096c080ece15.png)
![image](https://user-images.githubusercontent.com/48897387/54891423-49db5180-4ee8-11e9-8c01-c61c43106a03.png)
整体验证通过后，本来返回的resp这个response的参数有问题了。本来是提取text属性参数作为提起页面元素的参数，现在参数的值出现问题。

**Comment by haoyuanchanlai** [comment]
![image](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)


最终resp.text返回的一个js,该js应该在页面会重定向该js的url,是不是应该在页面该请求后重新在进行发起请求

**Comment by unraval** [comment]
这几天wechatsogou库貌似不能用了，里面方法取出来的信息都不一样了

**Comment by coinmeo** [comment]
本来的爬取信息为空的问题可以通过增加UA解决，上面提出解决方法当天测试还可以正常运行
今天重新测试时发现 会出现上面有人提到的问题
![image](https://user-images.githubusercontent.com/40992146/54895323-ff62d080-4ef9-11e9-84df-b9bd262c18cc.png)
不知道有没有大神可以帮助解决一下

**Comment by coinmeo** [comment]
![image](https://user-images.githubusercontent.com/40992146/54899878-4d80cf80-4f0c-11e9-8d79-3050cfda4bde.png)
上面如果出现URL匹配问题 要在URL请求时判断有没有加入微信搜狗的域名（上述仅仅是临时为了解决问题的写法，具体写到哪里合适可以自行决定）
![image](https://user-images.githubusercontent.com/40992146/54900207-545c1200-4f0d-11e9-8190-6a49af9b5d93.png)
后面对structuring中的方法也要进行一点修改，我自己简单测试了一下是可以运行的，数据初步测试是对的，最好的修改方法有待大神提出

**Comment by nimozzzz** [comment]
> ![image](https://user-images.githubusercontent.com/40992146/54899878-4d80cf80-4f0c-11e9-8d79-3050cfda4bde.png)
> 上面如果出现URL匹配问题 要在URL请求时判断有没有加入微信搜狗的域名（上述仅仅是临时为了解决问题的写法，具体写到哪里合适可以自行决定）
> ![image](https://user-images.githubusercontent.com/40992146/54900207-545c1200-4f0d-11e9-8190-6a49af9b5d93.png)
> 后面对structuring中的方法也要进行一点修改，我自己简单测试了一下是可以运行的，数据初步测试是对的，最好的修改方法有待大神提出

![QQ截图20190325155943](https://user-images.githubusercontent.com/41815560/54903751-98ecab00-4f17-11e9-8f0e-01d962b9ae71.png)
![QQ截图20190325160205](https://user-images.githubusercontent.com/41815560/54903768-a0ac4f80-4f17-11e9-989d-17bd5344084c.png)
![QQ截图20190325160340](https://user-images.githubusercontent.com/41815560/54903781-a73ac700-4f17-11e9-8743-50be89a7e5f4.png)

1.已在api.py添加if 判断 www.sogou.com 是否存在，2.已在structuring.py def get_gzh_info_by_history()添加response=request.get（URL，headers=headers），报错URL不存在，改为小写的url依然报错。

**Comment by coinmeo** [comment]
> > ![image](https://user-images.githubusercontent.com/40992146/54899878-4d80cf80-4f0c-11e9-8d79-3050cfda4bde.png)
> > 上面如果出现URL匹配问题 要在URL请求时判断有没有加入微信搜狗的域名（上述仅仅是临时为了解决问题的写法，具体写到哪里合适可以自行决定）
> > ![image](https://user-images.githubusercontent.com/40992146/54900207-545c1200-4f0d-11e9-8190-6a49af9b5d93.png)
> > 后面对structuring中的方法也要进行一点修改，我自己简单测试了一下是可以运行的，数据初步测试是对的，最好的修改方法有待大神提出
> 
> ![QQ截图20190325155943](https://user-images.githubusercontent.com/41815560/54903751-98ecab00-4f17-11e9-8f0e-01d962b9ae71.png)
> #------------------------------
> ![QQ截图20190325160205](https://user-images.githubusercontent.com/41815560/54903768-a0ac4f80-4f17-11e9-989d-17bd5344084c.png)
> #------------------------------
> ![QQ截图20190325160340](https://user-images.githubusercontent.com/41815560/54903781-a73ac700-4f17-11e9-8743-50be89a7e5f4.png)
> #------------------------------
> 1.已在api.py添加if 判断 [www.sogou.com](http://www.sogou.com) 是否存在，2.已在structuring.py def get_gzh_info_by_history()添加response=request.get（URL，headers=headers），报错URL不存在，改为小写的url依然报错。

这个url是在原先的text js文件里面的url，我是自己用正则匹配出来的，但是这个方法不治本，好像只能解决公众号的信息，公众号文章还是会报错，感觉像是sogou改了原先的网页设置，具体修改方法我也还在调试

**Comment by unraval** [comment]
@coinmeo 我参照你的方法在改，请求的url变了，现在返回的是
![image](https://user-images.githubusercontent.com/30172431/54906512-5b3f5080-4f1e-11e9-8619-8fb0bb443cb3.png)
这个url应该就是公众号信息页面，应该怎么提取

**Comment by unraval** [comment]
@

> ![image](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> 
> 最终resp.text返回的一个js,该js应该在页面会重定向该js的url,是不是应该在页面该请求后重新在进行发起请求

我也是遇到这种情况了   大佬怎么解决的

**Comment by haoyuanchanlai** [comment]
> @
> 
> > ![图片](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> > 最终resp.text返回的一个JS，JS该应该在页面会重定向该JS的网址，是不是应该在页面该请求后重新在进行发起请求
> 
> 我也是遇到这种情况了大佬怎么解决的

这个js跳转，我也暂时没有搞好。目前我想的办法是使用浏览器模拟去跑，本来是向用requests-html直接将模拟请求的，但是还是pytree一直报错，晚上回家用selenium试一试。但是这个只是暂时的。这个js的问题还要请大佬解决，最好整合带包里

**Comment by haoyuanchanlai** [comment]
> > @
> > > ![图片](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> > > 最终resp.text返回的一个JS，JS该应该在页面会重定向该JS的网址，是不是应该在页面该请求后重新在进行发起请求
> > 
> > 
> > 我也是遇到这种情况了大佬怎么解决的
> 
> 这个JS跳转，我也暂时没有搞好。目前我想的办法是使用浏览器模拟去跑，本来是向用请求，HTML直接将模拟请求的，但是还是pytree一直报错，晚上回家用硒试一试。但是这个只是暂时的。这个JS的问题还要请大佬解决，最好整合带包里

requests-html

**Comment by coinmeo** [comment]
> > > @
> > > > ![图片](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> > > > 最终resp.text返回的一个JS，JS该应该在页面会重定向该JS的网址，是不是应该在页面该请求后重新在进行发起请求
> > > 
> > > 
> > > 我也是遇到这种情况了大佬怎么解决的
> > 
> > 
> > 这个JS跳转，我也暂时没有搞好。目前我想的办法是使用浏览器模拟去跑，本来是向用请求，HTML直接将模拟请求的，但是还是pytree一直报错，晚上回家用硒试一试。但是这个只是暂时的。这个JS的问题还要请大佬解决，最好整合带包里
> 
> requests-html

我直接用正则把网址取出来再做request 但是后面还是多多少少出现一些BUG 不知道在搜狗微信修改之前的text应该返回什么样的页面

**Comment by unraval** [comment]
> > > > @
> > > > > ![图片](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> > > > > 最终resp.text返回的一个JS，JS该应该在页面会重定向该JS的网址，是不是应该在页面该请求后重新在进行发起请求
> > > > 
> > > > 
> > > > 我也是遇到这种情况了大佬怎么解决的
> > > 
> > > 
> > > 这个JS跳转，我也暂时没有搞好。目前我想的办法是使用浏览器模拟去跑，本来是向用请求，HTML直接将模拟请求的，但是还是pytree一直报错，晚上回家用硒试一试。但是这个只是暂时的。这个JS的问题还要请大佬解决，最好整合带包里
> > 
> > 
> > requests-html
> 
> 我直接用正则把网址取出来再做request 但是后面还是多多少少出现一些BUG 不知道在搜狗微信修改之前的text应该返回什么样的页面

之前的页面就是现在我们访问一个公众号的页面，所以可以直接etree解析到数据，现在变成了js，不知道怎么完了，老哥方不方便提供一下你的正则，晚上回去我在研究研究

**Comment by coinmeo** [comment]
> > > > > @
> > > > > > ![图片](https://user-images.githubusercontent.com/48897387/54892338-2dd9af00-4eec-11e9-9e32-59631d00309e.png)
> > > > > > 最终resp.text返回的一个JS，JS该应该在页面会重定向该JS的网址，是不是应该在页面该请求后重新在进行发起请求
> > > > > 
> > > > > 
> > > > > 我也是遇到这种情况了大佬怎么解决的
> > > > 
> > > > 
> > > > 这个JS跳转，我也暂时没有搞好。目前我想的办法是使用浏览器模拟去跑，本来是向用请求，HTML直接将模拟请求的，但是还是pytree一直报错，晚上回家用硒试一试。但是这个只是暂时的。这个JS的问题还要请大佬解决，最好整合带包里
> > > 
> > > 
> > > requests-html
> > 
> > 
> > 我直接用正则把网址取出来再做request 但是后面还是多多少少出现一些BUG 不知道在搜狗微信修改之前的text应该返回什么样的页面
> 
> 之前的页面就是现在我们访问一个公众号的页面，所以可以直接etree解析到数据，现在变成了js，不知道怎么完了，老哥方不方便提供一下你的正则，晚上回去我在研究研究

url = re.search('http://mp.weixin.qq.com/\S*==', text, flags=0).group()
只考虑这个JS界面里面的代码的话 用上面这个足够提取出来了 提取出来后处理一下编码问题
![image](https://user-images.githubusercontent.com/40992146/54913230-3dc5b300-4f2d-11e9-8d67-e8ff39747993.png)
我就用 他里面自带的这个处理编码的函数，没仔细看代码，应该可以跑过
后面公众号其他一些信息都可以取出来，但是下面这个图片取不出来，还在调试
api.get_article_content(article_content_url)['content_img_list']

上面那个替换域名的
![image](https://user-images.githubusercontent.com/40992146/54913538-eb38c680-4f2d-11e9-8909-a2d114e33998.png)
应该更换一下 如果用完全域名做判断，在取 文章原文时好像url错误

**Comment by coinmeo** [comment]
structuring.py get_article_by_history_json中
![image](https://user-images.githubusercontent.com/40992146/54933817-513a4380-4f58-11e9-891a-4c49a0066cb7.png)
structuring.py get_gzh_info_by_history中
![image](https://user-images.githubusercontent.com/40992146/54934272-2f8d8c00-4f59-11e9-932c-2097d51a921d.png)
这样勉强能实现读取数据，但也存在问题就是如果反复爬取，这里面的request也会需要验证码，还没有像作者那样集成，希望有大神能帮忙给个解决办法

**Comment by cnkailyn** [comment]
我最近的问题是使用代理调用搜索接口，验证码每次必现，此时我的解决办法是对WechatSogouAPI添加headers得以解决验证码必现问题：
![image](https://user-images.githubusercontent.com/34443073/54977929-c26e0b00-4fd9-11e9-9867-e68f2aaab570.png)
![image](https://user-images.githubusercontent.com/34443073/54977966-d6197180-4fd9-11e9-995d-5cbe8ff45892.png)

后续继续调用了获取文章详情的接口，此时报错，发现url没有host部分的信息，于是按照上文中其他小伙伴的方法添加了url中的host部分。继续运行，resp返回的text是js代码，于是正则解析获取到真正的url再次抓取得以解决。如图：
![image](https://user-images.githubusercontent.com/34443073/54977836-73c07100-4fd9-11e9-87c9-8cbcf22866bd.png)

**Comment by baby5** [comment]
@cnkailyn 你可以用微信搜狗的分享链接代替原链接，达到永久链接的目的

**Comment by NullYing** [comment]
搜狗的改动, url增加了两个参数:

https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6EzDJysI4ql5MPrOUp16838dGRMI7NnPqDGkmYxTfwlQ6AGViEYucJAwvDqyjOWdzwdyZxnEoYFrcPFymX5LZtev2fK-tii6gGM7tu6gg77ijXQiP1_-c_7wdMorsu3wAMKwBJ46PRKZcxLdca1pifHYFlvqk1ZgSdc1Mvp75N3NQ7x6HS01iIKUiiWOv1GPM&type=1&query=Yinyue8168&k=49&h=1

留意: 
&k=49&h=1

貌似通过js渲染的

**Comment by haoyuanchanlai** [comment]
> 搜狗的改动, url增加了两个参数:
> 
> https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6EzDJysI4ql5MPrOUp16838dGRMI7NnPqDGkmYxTfwlQ6AGViEYucJAwvDqyjOWdzwdyZxnEoYFrcPFymX5LZtev2fK-tii6gGM7tu6gg77ijXQiP1_-c_7wdMorsu3wAMKwBJ46PRKZcxLdca1pifHYFlvqk1ZgSdc1Mvp75N3NQ7x6HS01iIKUiiWOv1GPM&type=1&query=Yinyue8168&k=49&h=1
> 
> 留意:
> &k=49&h=1
> 
> 貌似通过js渲染的

这个在哪里可以看到啊，有没有来个debug图。。

**Comment by haoyuanchanlai** [comment]
![image](https://user-images.githubusercontent.com/48897387/55046341-34972c00-507c-11e9-8fd1-600be4710fb2.png)
![image](https://user-images.githubusercontent.com/48897387/55046351-3f51c100-507c-11e9-8006-11a30bf22ef2.png)
![image](https://user-images.githubusercontent.com/48897387/55046361-4c6eb000-507c-11e9-8252-a58f92f4d212.png)
如果直接获取公共号主页的连接的话，herf标签的连接会在页面上执行以上的js，如果没有渲染当前的js的话，会重新进入输入验证码的页面。这样会进入一个死循环，需要向上面的大佬一样在连接后添加&k=?&h=?才会进入主页面。进入页面是，是否还是调用js,正在调试

**Comment by NullYing** [comment]
``
    $("a").on("click contextmenu", function() {
        var b = Math.floor(100 * Math.random()) + 1
          , a = this.href.indexOf("url=")
          , c = this.href.indexOf("&k=");
        -1 !== a && -1 === c && (a = this.href.substr(a + 4 + b, 1),
        this.href += "&k=" + b + "&h=" + a)
    });
```
初步判断
k是两位随机数
h是url=在链接的位置

**Comment by HOUTASU** [comment]
> @cnkailyn 你可以用微信搜狗的分享链接代替原链接，达到永久链接的目的

大佬，这个分享链接怎么获取啊

**Comment by NullYing** [comment]
补充一下解决方法
```python
        href = "https://weixin.sogou.com" + account_div.find(uigs="account_name_0").get('href')
        b = int(get_random_num(2))
        a = href.find('url=')
        a = href[a + 4 + b:a + 4 + b + 1]
        article_url = "%s&k=%s&h=%s" % (href, b, a)
```

**Comment by NullYing** [comment]
跳到了下一个坑
```html
<meta content="always" name="referrer">\r\n
<script>\r\n    var url = \'\';\r\n    url += \'http://mp.w\';\r\n    url += \'eixin.qq.co\';\r\n    url += \'m/profile?s\';\r\n    url += \'rc=3&timest\';\r\n    url += \'amp=1553655\';\r\n    url += \'772&ver=1&s\';\r\n    url += \'ignature=MW\';\r\n    url += \'2FYuyD6TXnU\';\r\n    url += \'NQJCDJiS6SB\';\r\n    url += \'nTYpEhVfy83\';\r\n    url += \'dkALikgJH6I7e4G3iebjVAls5Eh3WoM9*caQ*7JF5io6pvnX7Og==\';\r\n    url.replace("@", "");\r\n    window.location.replace(url)\r\n</script>
```

**Comment by haoyuanchanlai** [comment]
> 跳到了下一个坑
> 
> ```
> <meta content="always" name="referrer">
> <script>
>     var url = '';
>     url += 'http://mp.w';
>     url += 'eixin.qq.co';
>     url += 'm/profile?s';
>     url += 'rc=3&timest';
>     url += 'amp=1553655';
>     url += '772&ver=1&s';
>     url += 'ignature=MW';
>     url += '2FYuyD6TXnU';
>     url += 'NQJCDJiS6SB';
>     url += 'nTYpEhVfy83';
>     url += 'dkALikgJH6I7e4G3iebjVAls5Eh3WoM9*caQ*7JF5io6pvnX7Og==';
>     url.replace("@", "");
>     window.location.replace(url)
> </script>
> ```

在代码将所有的url拼接，在replace下。只能这样了

**Comment by NullYing** [comment]
> > 跳到了下一个坑
> > ```
> > <meta content="always" name="referrer">
> > <script>
> >     var url = '';
> >     url += 'http://mp.w';
> >     url += 'eixin.qq.co';
> >     url += 'm/profile?s';
> >     url += 'rc=3&timest';
> >     url += 'amp=1553655';
> >     url += '772&ver=1&s';
> >     url += 'ignature=MW';
> >     url += '2FYuyD6TXnU';
> >     url += 'NQJCDJiS6SB';
> >     url += 'nTYpEhVfy83';
> >     url += 'dkALikgJH6I7e4G3iebjVAls5Eh3WoM9*caQ*7JF5io6pvnX7Og==';
> >     url.replace("@", "");
> >     window.location.replace(url)
> > </script>
> > ```
> 
> 在代码将所有的url拼接，在replace下。只能这样了

```
正则解决方案
        url_list = re.findall(r"url \+= '(.*)'", data)
        url = ''.join(url_list).replace('@', "")
```

**Comment by coinmeo** [comment]
> > > 跳到了下一个坑
> > > ```
> > > <meta content="always" name="referrer">
> > > <script>
> > >     var url = '';
> > >     url += 'http://mp.w';
> > >     url += 'eixin.qq.co';
> > >     url += 'm/profile?s';
> > >     url += 'rc=3&timest';
> > >     url += 'amp=1553655';
> > >     url += '772&ver=1&s';
> > >     url += 'ignature=MW';
> > >     url += '2FYuyD6TXnU';
> > >     url += 'NQJCDJiS6SB';
> > >     url += 'nTYpEhVfy83';
> > >     url += 'dkALikgJH6I7e4G3iebjVAls5Eh3WoM9*caQ*7JF5io6pvnX7Og==';
> > >     url.replace("@", "");
> > >     window.location.replace(url)
> > > </script>
> > > ```
> > 
> > 
> > 在代码将所有的url拼接，在replace下。只能这样了
> 
> 正则解决方案
> 
> ```python
>         url_list = re.findall(r"url \+= '(.*)'", data)
>         url = ''.join(url_list).replace('@', "")
> ```

那你这样正则匹配完还是要访问一次这个新的URL才能获得正确的resp.text吧

**Comment by NullYing** [comment]
> 这样正则匹配完还是要访问一次这个新的URL才能获得正确的

这都是小意思啦, 后面微信还有坑...搜狗的可以提pr了
我不是用这个库的,你们加油

**Comment by nimozzzz** [comment]
@coinmeo 
大佬按照您的方式修改了structuring.py get_article_by_history_json和
structuring.py get_gzh_info_by_history，返回的数据依然为空，是还有其他步骤吗？

**Comment by NullYing** [comment]
> get_article_by_history_json

无能为力哈,我是用scrapy的,无非就是referer, cookies的原因把

**Comment by haoyuanchanlai** [comment]
现在是直接输入验证码后，返回的text还是让我输验证码。已经走不下去了

**Comment by coinmeo** [comment]
> @coinmeo
> 大佬按照您的方式修改了structuring.py get_article_by_history_json和
> structuring.py get_gzh_info_by_history，返回的数据依然为空，是还有其他步骤吗？

我最近把这个项目给别人改的时候，他们源码包只改一个UA就可以运行 然后你说的返回数据为空我昨天最后测试的时候也出现了这个问题，但是中午测试的时候都是正常的，没有再具体测试原因了 搜狗反扒感觉越来越严厉了 我这边没用代理IP 自己的几个网都没封完了，验证码即使输入正确也是报错。

**Comment by coinmeo** [comment]
> 现在是直接输入验证码后，返回的text还是让我输验证码。已经走不下去了

你有DEBUG一下返回的text是什么url嘛

**Comment by haoyuanchanlai** [comment]
> > 现在是直接输入验证码后，返回的text还是让我输验证码。已经走不下去了
> 
> 你有DEBUG一下返回的text是什么url嘛

返回的是一个页面，但是的乱码的。只能看清楚有一个搜狗微信帮助的提示，应该就是验证码页面

**Comment by haoyuanchanlai** [comment]
> > 这样正则匹配完还是要访问一次这个新的URL才能获得正确的
> 
> 这都是小意思啦, 后面微信还有坑...搜狗的可以提pr了
> 我不是用这个库的,你们加油
我准备还是用浏览器模拟把。不知道行不行，不要想淘宝一样，需要登入才给搜索。

**Comment by ever391** [comment]
问题解决了，真的很爽，困扰了好几天。。。。。

**Comment by haoyuanchanlai** [comment]
> 问题解决了，真的很爽，困扰了好几天。。。。。

有啥解决的好办法吗？

**Comment by NullYing** [comment]
微信的坑，bs4解析页面会抛线程异常，用xpath没问题，你们加油，方法都在上面，实现方式不同而已

**Comment by Ahaaaaaa** [comment]
验证码即使是正确的也报错怎么解决

**Comment by coinmeo** [comment]
> 验证码即使是正确的也报错怎么解决

换一个IP 爬取频繁被封了可能 我跟你出现过同样的情况 换网就好了 反正隔了一天也没有被放出来

**Comment by nimozzzz** [comment]
各位有完整的解决方案了吗？<meta content="always" name="referrer">信息完全没有找到，需要大佬的帮助，QQ1714881214因为毕设需要用到（可以付费求指导），自己尝试了selenium，但是会被sogou识别，学艺不精实在没有办法了

**Comment by callmeliuchu** [comment]
我是模拟浏览器的，可以慢慢爬

**Comment by nimozzzz** [comment]
> 我是模拟浏览器的，可以慢慢爬

我的会一直要求我输入验证码？

**Comment by callmeliuchu** [comment]
那是因为你是直接用公众号的url去访问，你得真实模拟浏览器点击事件，点击公众号后新开了一个页面就不会有验证码了，我的理解是从父页面新开一个新页面后的请求应该附带了父页面的信息

**Comment by ever391** [comment]
开了QQ群，一起来讨论解决微信反爬的问题吧：662500882

**Comment by ever391** [comment]
> > 问题解决了，真的很爽，困扰了好几天。。。。。
> 
> 有啥解决的好办法吗？

假象！然并卵， 崩溃中！

**Comment by haoyuanchanlai** [comment]
如果大家在爬取时，输入验证码后。如下图所示api.py126行已经添加UA标识，填写正确的验证码后还是报错的情况。建议大家，在PC端搜索你要的公众号，如图二所示，在F12下，将公众号的连接复制出来，在浏览器打开,输入验证码正确后，在重新起代码跑一下应该就可以了。后面返回的text是一个js,可以参照下图3的写法拼接下目标地址的url就可以正常的访问公众号详情页面了。上次的js是+4，今天好像改成了+15了，大家试试啊
![image](https://user-images.githubusercontent.com/48897387/55220179-a5d40c00-5241-11e9-9ca6-c5a602412d38.png)
![image](https://user-images.githubusercontent.com/48897387/55220423-36125100-5242-11e9-90b8-55ce3c27845e.png)
![image](https://user-images.githubusercontent.com/48897387/55220649-b042d580-5242-11e9-9eda-e38b7eb8e892.png)

**Comment by haoyuanchanlai** [comment]
> 如果大家在爬取时，输入验证码后。如下图所示api.py126行已经添加UA标识，填写正确的验证码后还是报错的情况。建议大家，在PC端搜索你要的公众号，如图二所示，在F12下，将公众号的连接复制出来，在浏览器打开,输入验证码正确后，在重新起代码跑一下应该就可以了。后面返回的text是一个js,可以参照下图3的写法拼接下目标地址的url就可以正常的访问公众号详情页面了。上次的js是+4，今天好像改成了+15了，大家试试啊
> ![image](https://user-images.githubusercontent.com/48897387/55220179-a5d40c00-5241-11e9-9ca6-c5a602412d38.png)
> ![image](https://user-images.githubusercontent.com/48897387/55220423-36125100-5242-11e9-90b8-55ce3c27845e.png)
> ![image](https://user-images.githubusercontent.com/48897387/55220649-b042d580-5242-11e9-9eda-e38b7eb8e892.png)

应该暂时没有问题，已经跑了一天了。建议频率不要太频繁，

**Comment by coinmeo** [comment]
> 输入验证码正确后
如果要挂服务器上自动运行的话还是要像原作者一样接入处理验证码的函数吧 然后我才接入打码平台 不知道有没有大佬帮忙解决一下

**Comment by Chyroc** [comment]
在 https://github.com/Chyroc/WechatSogou/issues/235 讨论

**Comment by gaoyuanwang** [comment]
/link?开头的链接后面会拼上随机参数，这个参数的方法在搜狗搜索页的最后是有的，访问拼出来的js页面最好使用访问搜狗搜索页同样的代理和cookie
