### ISSUE TITLE
多了一层 /link?url= 跳转

### ISSUE THREAD

**Issue by unraval** [Chyroc/WechatSogou#235]
wechatsogou库这几天是不能用了吗，里面封装出来的方法，现在获取到的信息都跟之前不一样了

**Comment by ever391** [comment]
微信改版了，虽然按新的方式调了，但还是没有通过，也就是还没有发版，希望作者快点处理好，可以先发一个小版本号！

**Comment by Pjer-zhang** [comment]
啊  原来不止我一个人遇到这样的问题啦，hhh

**Comment by crisis111** [comment]
作者处理好了吗？我的抓取也不能用了

**Comment by ever391** [comment]
近最近几天在疯狂加班加点的处理，但是现在微信的反爬策略更严格了，后台的限制与认证外加IP更严了。。。。

**Comment by unraval** [comment]
微信有没有接口之类的，这样爬太麻烦了

**Comment by baby5** [comment]
可以注册公众号后从内部爬取

**Comment by zhxxmu** [comment]
我也发现不能用了，提示信息如下：
 File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 370, in get_gzh_article_by_history
    gzh_list = self.get_gzh_info(keyword, unlock_callback_sogou, identify_image_callback_sogou)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 192, in get_gzh_info
    info = self.search_gzh(wecgat_id_or_name, 1, unlock_callback, identify_image_callback)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 239, in search_gzh
    identify_image_callback=identify_image_callback)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 111, in __get_by_unlock
    resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 65, in __get
    raise WechatSogouRequestsException('WechatSogouAPI get error', resp)
wechatsogou.exceptions.WechatSogouRequestsException: ('WechatSogouAPI get error', <Response [502]>)

**Comment by unraval** [comment]
> 可以注册公众号后从内部爬取

试过了，也是获取不到数据

**Comment by callmeliuchu** [comment]
之前直接拿爬取的公众号url就可以获取所有文章的url,现在得从弹出的子页面发送请求才行，不然会有验证码并且怎么输入都不对

**Comment by luoqishuai** [comment]
> 
> 
> 可以注册公众号后从内部爬取

是微信公众平台，然后输入转载源吗？这种方法不会封号吗

**Comment by mrlyhao** [comment]
现在文章后边有两个随机参数，估计是js生成的，比较难搞呀

**Comment by mrlyhao** [comment]
随机参数是根据url生成的。
```
    def parse_url(url):
        """
            var b = Math.floor(100 * Math.random()) + 1
              , a = this.href.indexOf("url=")
              , c = this.href.indexOf("&k=");
            -1 !== a && -1 === c && (a = this.href.substr(a + 15 + b, 1),
            this.href += "&k=" + b + "&h=" + a)
        """
        b = math.floor(random.random() * 100) + 1
        a = url.find("url=")
        c = url.find("&k=")
        if a != -1 and c == -1:
            a = url[a + 15 + b]
 
        url = url + "&k=" + str(b) + "&h=" + str(a)
        return url
```

**Comment by zhxxmu** [comment]
今天更新了api.py的代码之后，运行时提示以下错误：
wechatsogou.exceptions.WechatSogouRequestsException: ('WechatSogouAPI get img', <Response [200]>)
请问该如何处理？

**Comment by czlhs** [comment]
> 随机参数是根据url生成的。
> 
> ```
>     def parse_url(url):
>         """
>             var b = Math.floor(100 * Math.random()) + 1
>               , a = this.href.indexOf("url=")
>               , c = this.href.indexOf("&k=");
>             -1 !== a && -1 === c && (a = this.href.substr(a + 15 + b, 1),
>             this.href += "&k=" + b + "&h=" + a)
>         """
>         b = math.floor(random.random() * 100) + 1
>         a = url.find("url=")
>         c = url.find("&k=")
>         if a != -1 and c == -1:
>             a = url[a + 15 + b]
>  
>         url = url + "&k=" + str(b) + "&h=" + str(a)
>         return url
> ```

又改了， a = url[a+28+b] 了。。。

**Comment by siminwendy** [comment]
> > 随机参数是根据url生成的。
> > ```
> >     def parse_url(url):
> >         """
> >             var b = Math.floor(100 * Math.random()) + 1
> >               , a = this.href.indexOf("url=")
> >               , c = this.href.indexOf("&k=");
> >             -1 !== a && -1 === c && (a = this.href.substr(a + 15 + b, 1),
> >             this.href += "&k=" + b + "&h=" + a)
> >         """
> >         b = math.floor(random.random() * 100) + 1
> >         a = url.find("url=")
> >         c = url.find("&k=")
> >         if a != -1 and c == -1:
> >             a = url[a + 15 + b]
> >  
> >         url = url + "&k=" + str(b) + "&h=" + str(a)
> >         return url
> > ```
> 
> 又改了， a = url[a+28+b] 了。。。

你好，请问是在哪里找到的是+28，之前+15，和在之前的+4 我都找到了那个Js，你说的+28在哪里发现的，多谢多谢

**Comment by czlhs** [comment]
> > > 随机参数是根据url生成的。
> > > ```
> > >     def parse_url(url):
> > >         """
> > >             var b = Math.floor(100 * Math.random()) + 1
> > >               , a = this.href.indexOf("url=")
> > >               , c = this.href.indexOf("&k=");
> > >             -1 !== a && -1 === c && (a = this.href.substr(a + 15 + b, 1),
> > >             this.href += "&k=" + b + "&h=" + a)
> > >         """
> > >         b = math.floor(random.random() * 100) + 1
> > >         a = url.find("url=")
> > >         c = url.find("&k=")
> > >         if a != -1 and c == -1:
> > >             a = url[a + 15 + b]
> > >  
> > >         url = url + "&k=" + str(b) + "&h=" + str(a)
> > >         return url
> > > ```
> > 
> > 
> > 又改了， a = url[a+28+b] 了。。。
> 
> 你好，请问是在哪里找到的是+28，之前+15，和在之前的+4 我都找到了那个Js，你说的+28在哪里发现的，多谢多谢

搜索页面最下面一个script节点，榜在on-click上面的，这个是动态变化的，我现在才发现，我现在是直接读出js来判断。

**Comment by Chyroc** [comment]
@unraval @ever391 @Pjer-zhang @crisis111 @baby5 https://github.com/Chyroc/WechatSogou/pull/238 大家 review 下

**Comment by anexplore** [comment]
> > 可以注册公众号后从内部爬取
> 
> 是微信公众平台，然后输入转载源吗？这种方法不会封号吗
同问
