### ISSUE TITLE
结果模版更新了

### ISSUE THREAD

**Issue by kiruto** [Chyroc/WechatSogou#24]
api.py WechatSogouApi.search_gzh_info()方法解析新模版出错了
`cache_re = re.split(u'微信号：|功能介绍：|认证：|最近文章：', cache_list[0])`
今天的微信id列表页里，这行文字是这样的：
`u'XXX微信号:XXXXXX月发文XX篇    平均阅读XXXXX'`

**Comment by Chyroc** [comment]
已更新

**Comment by kiruto** [comment]
Thanks！
