### ISSUE TITLE
验证码加载问题

### ISSUE THREAD

**Issue by Wuxuewendao** [Chyroc/WechatSogou#251]
这是测试代码
> import wechatsogou
ws_api = wechatsogou.WechatSogouAPI()
data = ws_api.search_article('南京航空航天大学')
print(data)

这是报错，验证码加载不出来
> Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/weixinspider/test.py", line 10, in <module>
    for item in data:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wechatsogou\api.py", line 359, in search_article
    session=session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wechatsogou\api.py", line 118, in __get_by_unlock
    unlock_platform(url=url, resp=resp, session=session, unlock_callback=unlock_callback, identify_image_callback=identify_image_callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wechatsogou\api.py", line 77, in __unlock_sogou
    raise WechatSogouRequestsException('WechatSogouAPI get img', resp)
wechatsogou.exceptions.WechatSogouRequestsException: ('WechatSogouAPI get img', <Response [200]>)

**Comment by Wuxuewendao** [comment]
截图
https://oss.aiquit.cn/2019/04/2019040304013832.png

**Comment by zhxxmu** [comment]
我早上也会出现这个错误，刚才又执行发现不会了，可以弹出验证码图片。

**Comment by zhxxmu** [comment]
今天早上执行程序，也会报这个错误提示了。
raise WechatSogouRequestsException('WechatSogouAPI get img', resp)
wechatsogou.exceptions.WechatSogouRequestsException: ('WechatSogouAPI get img', <Response [200]>)

**Comment by torchina** [comment]
**聊天室 - 没有自我审查**

**https://gitter.im/torchina/community**

**Tor 浏览器 8.0.8 - 绕过gfw**

![Tor Browser](https://github.com/torchina/get/blob/master/2019-04-06_22-27-39.png?raw=true)

**https://torchina.github.io/get**

**Comment by ritalyd** [comment]
同有这个问题，换了几个IP都不太行，求大神解答TT

**Comment by unraval** [comment]
> WechatSogouRequestsException

这个问题你解决了没

**Comment by hhrensheng** [comment]
我也有这个错误，返回的是 Response [403] 。是因为ip被封了吗

**Comment by Chyroc** [comment]
fixed by https://github.com/Chyroc/WechatSogou/pull/254
