### ISSUE TITLE
获取最新十篇文章接口报错

### ISSUE THREAD

**Issue by hhrensheng** [Chyroc/WechatSogou#253]
报错信息如下：
![image](https://user-images.githubusercontent.com/29398035/55849221-70ed8080-5b82-11e9-8568-21bb7fd6ecb7.png)
请求‘http://weixin.sogou.com/antispider/util/seccode.php’，提示403
本地环境：centos 7 python：2.7

**Comment by Chyroc** [comment]
fixed by https://github.com/Chyroc/WechatSogou/pull/254
