### ISSUE TITLE
get_gzh_article_by_history该方法搜索公众号概率返回空字典

### ISSUE THREAD

**Issue by chenjiawei514** [chyroc/WechatSogou#264]
版本 4.5.4
在使用过程中发现，get_gzh_article_by_history该方法在使用中概率会返回空字典{}

**Comment by OrangeGeeker** [comment]
> 版本 4.5.4
> 在使用过程中发现，get_gzh_article_by_history该方法在使用中概率会返回空字典{}

我也有这个问题，有处理方法吗？

**Comment by hhrensheng** [comment]
> > 版本 4.5.4
> > 在使用过程中发现，get_gzh_article_by_history该方法在使用中概率会返回空字典{}
> 
> 我也有这个问题，有处理方法吗？

应该是ip被禁了，挂代理试试吧。

**Comment by genezx** [comment]
应该不是IP被禁吧，因为浏览器能正常获取文章列表，但是这个api不行。

**Comment by BlackSheepwall0305** [comment]
同问

**Comment by wangz** [comment]
是不是已经被搜狗识别给拦截了

**Comment by btlxw2005** [comment]
同问 这个怎么办？
