### ISSUE TITLE
请问一下在linux下怎么获取到验证码呢？

### ISSUE THREAD

**Issue by Wdiviner** [Chyroc/WechatSogou#279]
在win10下会自动弹出图片显示器显示验证码，请问一下在linux下该怎么处理才能拿到验证码呢？谢谢。

**Comment by dengsibao** [comment]
自动获取验证码，不会弹出验证码的框，主要是要实现identify_image_callback。
源代码有实现的例子

```py
def __identify_image_callback(img, code):
    try:
        username = os.environ['rk_username']
        password = os.environ['rk_password']
        id_ = os.environ['rk_id']
        key = os.environ['rk_key']
        rc = RClient(username, password, id_, key)
        result = rc.rk_create(img, code)
        print('验证码：', result['Result'])
        return result['Result']
    except Exception:
        raise Exception('识别验证码错误')

```
下面是具体实现
```py
def identify_image_callback_ruokuai_sogou(img):
    return __identify_image_callback(img, 3060)


def identify_image_callback_ruokuai_weixin(img):
    return __identify_image_callback(img, 3040)
```

最后直接调用就可以：
```py
ws_api.get_gzh_info('bitewu666'，identify_image_callback = rk.identify_image_callback_ruokuai_sogou)
```

**Comment by Wdiviner** [comment]
> ```python
> identify_image_callback = rk.identify_image_callback_ruokuai_sogou
> ```

您好，我把这些代码加进去以后该怎么重新编译打包呢？

**Comment by Wdiviner** [comment]
> 自动获取验证码，不会弹出验证码的框，主要是要实现identify_image_callback。
> 源代码有实现的例子
> 
> ```python
> def __identify_image_callback(img, code):
>     try:
>         username = os.environ['rk_username']
>         password = os.environ['rk_password']
>         id_ = os.environ['rk_id']
>         key = os.environ['rk_key']
>         rc = RClient(username, password, id_, key)
>         result = rc.rk_create(img, code)
>         print('验证码：', result['Result'])
>         return result['Result']
>     except Exception:
>         raise Exception('识别验证码错误')
> ```
> 
> 下面是具体实现
> 
> ```python
> def identify_image_callback_ruokuai_sogou(img):
>     return __identify_image_callback(img, 3060)
> 
> 
> def identify_image_callback_ruokuai_weixin(img):
>     return __identify_image_callback(img, 3040)
> ```
> 
> 最后直接调用就可以：
> 
> ```python
> ws_api.get_gzh_info('bitewu666'，identify_image_callback = rk.identify_image_callback_ruokuai_sogou)
> ```

 您好，我把这些代码加进去以后该怎么重新编译打包呢？怎么才能运行起来呢？

**Comment by Wdiviner** [comment]
---
def __identify_image_callback(img, code):
    try:
        username = os.environ['rk_username']
        password = os.environ['rk_password']
        id_ = os.environ['rk_id']
        key = os.environ['rk_key']
        rc = RClient(username, password, id_, key)
        result = rc.rk_create(img, code)
        print('验证码：', result['Result'])
        return result['Result']
    except Exception:
        raise Exception('识别验证码错误')
---
该方法使用了三方付费接口
