### ISSUE TITLE
文章列表页也可能出现验证码

### ISSUE THREAD

**Issue by kiruto** [Chyroc/WechatSogou#29]
验证码页面source code：https://gist.github.com/kiruto/28616c5f9dcbe994b8b8b058e48c75b8
抛异常在WechatSogouBasic._get函数中，我这用的js引擎解析也偶尔会出这个问题。
这个验证码出现在从搜索公众号页面进入到该公众号的最近文章列表页时出现。也就是说可能会获取不到文章列表页。
请问这个是否也需要处理？

**Comment by kiruto** [comment]
抱歉，这个才是source code，上面给的是js解析后的source。
https://gist.github.com/kiruto/9c0104850ec8810a838347fcc641a73e

**Comment by Chyroc** [comment]
@kiruto ， 这个应该是处理过的，请问是不是验证码输错了，这个也会在_get里面报错。
请贴出具体的报错信息~

**Comment by kiruto** [comment]
如果也是处理过的，应该是验证码模版变了。但是我看代码逻辑应该是未经处理的。
之前的验证码模版文案是：用户您好，您的访问过于频繁，为确认本次访问为正常用户行为，需要您协助验证
我贴出来的Html中，模版文案是：为了您的安全请输入验证码

具体报错我现在不好找了，是过了_get方法，在api.py WechatSogouBasic.get_gzh_message方法中，return self._deal_gzh_article_dict(self._get_gzh_article_by_url_dict(text))这里解析出错了。

我修复了这个问题，但是我的实现和你的不太一样，我用V8解析的html。。。所以提不了PR。。。。。抱歉otz

**Comment by yfhlearnios** [comment]
@kiruto 你好，想问一下，文章列表的验证码你是怎么解决了？

**Comment by yfhlearnios** [comment]
@Chyroc 你好，我现在经常会在列表界面遇到验证码，当我输入验证码发送了post请求之后，会报一个“{"ret":501,"errmsg":"","cookie_count":0}”这样的返回信息，应该是不识别我的数据。这个是什么情况？

**Comment by wanghj321** [comment]
@kiruto   @Chyroc  想问下验证码是怎么解决的呢？

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/95
