### ISSUE TITLE
导入文件后有bug

### ISSUE THREAD

**Issue by Qmoliang** [Chyroc/WechatSogou#31]
为什么会提示No module named base？这个base库是哪来的

**Comment by Chyroc** [comment]
抱歉，在修改整个项目，误删了，已修正，请git pull 更新。

**Comment by istommao** [comment]
@Chyroc 不打算upload 到 pypi吗？

**Comment by Chyroc** [comment]
@istommao https://github.com/Chyroc/WechatSogou/pull/46

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/47
