### ISSUE TITLE
pip 安装 No module named requests 什么情况

### ISSUE THREAD

**Issue by istommao** [Chyroc/WechatSogou#59]
![image](https://cloud.githubusercontent.com/assets/5070879/24360856/05c44050-133b-11e7-849e-17cd66357de4.png)

**Comment by Chyroc** [comment]
`pip install requests`

**Comment by istommao** [comment]
你得setup.py 里得 install_requires 好像 没生效 不知道什么情况，我手动安装了 pillow lxml requests 这些需要安装得东西后才成功

**Comment by Chyroc** [comment]
好吧。。
