### ISSUE TITLE
调用方法search_gzh_info()搜索公众号时，获取到的结果中wechatid为‘’

### ISSUE THREAD

**Issue by huansoo** [Chyroc/WechatSogou#62]
api.py中的方法search_gzh_info()获取到的变量info值为：u'微信号：autohomeweixin'，调用方法
info = re.split('微信号:|月发文|篇|平均阅读', info)后，info数组的长度为1，故取wechatid = info[1]时会报错，获取到的所有wechatid都为‘’

**Comment by yyNoMoon** [comment]
将获取到的info转换成utf8格式再用info = re.split('微信号:|月发文|篇|平均阅读', info)得到info[1],info[1]里面就是微信号了：
info = info.encode('utf8','ignore')
info = re.split('微信号:|月发文|篇|平均阅读', info)
wechatid = info[1]

**Comment by Chyroc** [comment]
@yyNoMoon 方便提一个pr吗，就是把你的修改刚上来

**Comment by yyNoMoon** [comment]
[search_gzh_info.txt](https://github.com/Chyroc/WechatSogou/files/1155244/search_gzh_info.txt)

**Comment by yyNoMoon** [comment]
api.py文件里这一个函数里只修改了一点点，萌新不敢改太多。。。 @Chyroc

**Comment by Chyroc** [comment]
@yyNoMoon 额，你知道怎么提pr（pull request）吗，步骤如下：

先点击本repo右上角的fork

然后 `git clone <fork之后的地址>`

然后 `git checkout -b <branch-name>`切换都新的分支，准备些代码

然后修改代码，保证可以运行，去除测试用的log和print，然后

```
git add <filename>            //这个filename是将你刚刚改的文件名
git commit -m "一些解释"
git push --set-upstream origin <branch-name>       //将本地修改的代码推送到远程（也就是github上）
```

然后你去你fork之后的地址，点击 创建一个新的 pull request

我就能看到了

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/92

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/issues/70
