### ISSUE TITLE
无法正确解析wechatid

### ISSUE THREAD

**Issue by imlijunda** [Chyroc/WechatSogou#70]
WechatSogouApi.search_gzh_info无法获取wechatid

possible workaround:
wechatid = get_elem_text(li.xpath('div/div[2]/p[2]/label')[0])

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/83

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/issues/83

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/issues/62
