### ISSUE TITLE
列表页验证码有办法绕过吗？

### ISSUE THREAD

**Issue by Christophy** [Chyroc/WechatSogou#71]
现在从公众号搜索页跳转到公众号最近文章的列表页，每次都会进入验证码页面，我用了 time.sleep()来增加访问延迟，结果还是没有效果。不知道搜狗这个验证机制是怎么样实现的，有没有办法绕开呢？
```
def get_gzh_message() 中：
            time.sleep(5)
            gzh_info = self.get_gzh_info(wechatid)
            time.sleep(5)
            print "search gzh!"
            url = gzh_info['url']
            time.sleep(10)
            text = self._get_gzh_article_by_url_text(url)
            print "enter list page"
            time.sleep(1)
```

**Comment by yfhlearnios** [comment]
@Christophy 兄弟，最近有好办法了吗？能绕过验证码问题的办法

**Comment by wanghj321** [comment]
<div class="page_verify">
    <p class="page_loading_desc web_only" id="loading">正在跳转中...</p>
    <div class="verify_box " id="verify_result"> 
        <div class="weui_cells weui_cells_form">
            <div class="weui_cell weui_vcode verifycode">
                <div class="weui_cell_hd wap_only"><label class="weui_label">验证码</label></div>
                <div class="weui_cell_bd weui_cell_primary frm_input_box">
                    <input class="weui_input frm_input" id="input" placeholder="请输入验证码" maxlength="4">
                </div>
                <div class="weui_cell_ft">
                    <i class="weui_icon_warn wap_only"></i>
                    <img id="verify_img">
                </div>
                <a href="javascript:;" id="verify_change" class="btn_change web_only">换一张</a>
            </div>
        </div>
        <div class="weui_cells_tips">为了保护你的网络安全，请输入验证码</div>
        <p class="verify_err web_only" >
            <i class="weui_icon_warn"></i>
            <span class="verify_err_msg" >验证码有误</span>
        </p>
        <div class="weui_btn_area btn_box">
            <a class="weui_btn weui_btn_primary btn" href="javascript:" id="bt">确定</a>
        </div>
    </div>
</div>
想同问有没有解决办法

**Comment by yfhlearnios** [comment]
@wanghj321 你是想要人工协助解决还是单纯靠机器解决？

**Comment by wanghj321** [comment]
@yfhlearnios 我现在是在服务器写了个爬虫去抓取公众号的文章，但是最近发现ip好像被封了，访问的时候返回的都是这个需要输入验证码的页面，就想看有没有什么解决办法，在代码上解决绕过去。不知道你有没有什么解决方案？我试了加代理什么的都不行

**Comment by Christophy** [comment]
@yfhlearnios 还没找到。我目前用的那个打码软件，但是我对爬取速度没有啥要求，所以想通过延迟的方法绕过。毕竟每次进列表页都要验证码。。

**Comment by wanghj321** [comment]
@yfhlearnios 你说若快的那个软件？ 方便加个qq吗？想找你了解下。

**Comment by wanghj321** [comment]
@yfhlearnios 我的qq号：448120231

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/92
